// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

type Mutation struct {
}

type NewCompany struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

type NewProfile struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	CompanyID *int32 `json:"companyID,omitempty"`
}

type Profile struct {
	ID        int32    `json:"id"`
	Name      string   `json:"name"`
	Email     string   `json:"email"`
	CompanyID *int32   `json:"companyID,omitempty"`
	Company   *Company `json:"company,omitempty"`
}

type Query struct {
}

type UpdateCompany struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

type UpdateProfile struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CompanyID *int32 `json:"companyID,omitempty"`
}
